# fly.toml app configuration file generated for rapha-medical-ai-backend on 2026-04-20T10:27:02+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rapha-medical-ai-backend'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_VERSION = '1.0.0'
  DEBUG = 'false'
  MODEL_NAME = 'dummy-v0.1'
  REQUIRE_API_KEY = 'false'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25

[checks]
  [checks.health]
    port = 8000
    type = 'http'
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/v1/health'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
